---
## Obtain Piecewise, M-Lab's Telescope Utility, and the current MaxMind CSV
- name: Fetch M-Lab's Telescope Utility
  git:
    repo: https://github.com/m-lab/telescope.git
    dest: "{{ base_path }}/telescope/"

- name: Create an alias for telescope in the deploy users' profile
  shell: echo 'alias telescope="PYTHONPATH=/opt/telescope python /opt/telescope/main.py"' >> .profile

- name: Fetch Piecewise
  git:
    repo: "{{ git_repo }}"
    dest: "{{ base_path }}/piecewise.git"
    version: "{{ piecewise_commit }}"

- name: Deploy Piecewise
  file:
    src: "{{ base_path }}/{{ project_name }}.git/{{ item }}"
    dest: "{{ base_path }}/{{ item }}"
    state: link
  with_items:
    - piecewise
    - piecewise_web
    - collector

- name: Install required python modules for piecewise and telescope
  pip:
    requirements: "{{ item }}"
    state: latest
  with_items:
    - "{{ base_path }}/telescope/requirements.txt"
    - "{{ base_path }}/{{ project_name }}/requirements.txt"

- name: Install additional python modules
  pip: 
    name: "{{ item }}"
    state: latest
  with_items: 
    - ipaddress
    - bigquery

- name: Get the latest MaxMind CSV
  unarchive:
    remote_src: yes
    src: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum2.zip
    dest: /tmp/
    creates: /tmp/GeoIPASNum2.csv

- name: Generate Letsencrypt certs
  command: "certbot certonly --standalone -n -d {{ site_fqdn }} -m {{ site_contact }} --agree-tos"
  when: env == "production"

## Create SSL directory for self-signed Certificate Keys
- name: Create private directory for SSL Keys
  file:
    path: /etc/ssl/private
    state: directory
  when: env == "development"

- name: create self-signed ssl cert/key - development only!
  command: >
    openssl req -new -nodes -x509
    -subj "/C={{ site_country }}/ST={{ site_state }}/L={{ site_city }}/O={{ site_ou }}/CN={{ site_fqdn }}" -days 3650
    -keyout {{ self_signed_ssl_key_path }} -out {{ self_signed_ssl_cert_path }} -extensions v3_ca
  args:
    creates: "{{ self_signed_ssl_cert_path }}"
  when: env == "development"

## Deploy system configuration files common to all systems
- name: Deploy common system configuration files
  copy:
    src: "files/common/"
    dest: /
    owner: root
    group: root

- name: Create /etc/piecewise directory
  file:
    path: /etc/{{ project_name }}
    state: directory

## Logs
- name: Create Piecewise log directory
  file:
    path: /var/log/{{ project_name }}/
    state: directory

## Initialize the Piecewise database and setup its schema
- name: Create the piecewise database in postgres
  postgresql_db:
    name: "{{ database_name }}"
    state: present
  become: true
  become_user: postgres

- name: Setup the piecewise database schema
  command: psql -U {{ database_user }} -d {{ database_name }} -f {{ base_path }}/piecewise/setup.sql
  become: true
  become_user: postgres

## Apply local server files and customizations
- name: Copy geo data to server
  copy:
    src: "../local_customizations/geofiles"
    dest: "{{ site_path }}/"

- name: Copy extra_data.py server
  copy:
    src: "../local_customizations/extra_data.py"
    dest: "{{ base_path }}/{{ project_name }}/"

- name: Add the file defining the map center
  template:
    src: "templates/map_center.js"
    dest: "{{ site_path }}/js/center.js"

## Add the site's index file, built from templated values
- name: Add the map site index page
  template:
    src: "templates/index.html"
    dest: "{{ site_path }}/index.html"
    force: yes

- name: Ingest census blocks to postgres
  command: > 
    ogr2ogr -overwrite -f PostgreSQL -t_srs {{ shape_projection }} -nln {{ layer_name }}
    -nlt {{ geometry_type }} 'PG:user={{ database_user }} dbname={{ database_name }}'
    {{ site_path }}/geofiles/{{ shape_file }}
  become: true
  become_user: postgres

- name: Install piecewise configuration
  template:
    src: "templates/piecewise_config"
    dest: /etc/piecewise/config.json
    force: yes

- name: Update bigquery config
  template:
    src: "templates/bigquery.py"
    dest: "{{ base_path }}/piecewise/piecewise/bigquery.py"
    force: yes

- name: Restart uwsgi so piecewise config is detected
  service:
    name: uwsgi
    state: restarted

- name: Run extra_data.py in the /opt/piecewise directory
  command: python extra_data.py arg1
  args:
    chdir: "{{ base_path }}/{{ project_name }}"
  become: true
  become_user: postgres
