---
- hosts: all
  tasks:
    - include: playbooks/debian_hosts_tasks.yml
      become: true
      become_user: root
      when:
        - ansible_distribution == "Debian"
        - ansible_distribution_major_version == "8"
    - include: playbooks/rhel_hosts_tasks_testing.yml
      become: true
      become_user: root
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"

    - include: playbooks/all_hosts_tasks.yml
      become: true
      become_user: root
